### ISSUE TITLE
[上海, 漕河泾开发区][25K+][一下科技] Go工程师

### ISSUE THREAD

**Issue by jony4** [GoHackers/jobs#3]
## 1 公司名称
一下科技（上海）

## 2 公司地址
上海市徐汇区漕河泾开发区地铁口，民润大厦。

## 3 公司网站
http://www.yixia.com/

## 4 公司简介
炫一下（北京）科技有限公司2011年8月成立于北京，领先的移动互联网基础服务提供商，先后获得晨兴、红点、红杉资本、Star VC、新浪微博、东方卫视等投资，2016年11月21日宣布已完成E轮5亿美金融资。

公司创立以来，以技术为驱动，致力于为用户提供便捷的移动多媒体服务，构建开放一站式的移动互联网服务。目前公司员工1500人，是一群来自于暴风影音、搜狐、酷6网、新浪等富有激情、勇于创新、专注技术、执着梦想的年轻人，拥有多年的业内一流的视频编解码经验以及多年的视频多媒体运营能力。

炫一下（北京）科技有限公司旗下拥有新浪视频、新浪微博独家战略合作产品秒拍、业内首款领先的移动多媒体视频框架Vitamio及移动端视频全能播放器VPlayer。截至目前多媒体视频框架Vitamio拥有800多名开发者，全球1000多款应用在使用，总下载量2亿。

基金简介：基金初期规模为1.2亿美元，主要由一下科技、新浪、红杉、德同等国内知名企业、顶级投资机构等共同出资，投资方向为：TMT领域。

旗下产品：

秒拍：http://www.miaopai.com/

小咖秀：http://xiaokaxiu.com/

一直播：http://yizhibo.com/

VPlayer 全能播放器：https://vplayer.net/?locale=zh-CN

Vitamio 多媒体 SDK：http://www.vitamio.org/en/

波波视频  https://itunes.apple.com/cn/app/%E6%B3%A2%E6%B3%A2%E8%A7%86%E9%A2%91-%E4%B8%80%E7%9C%8B%E5%B0%B1%E6%9C%89%E5%A5%BD%E5%BF%83%E6%83%85/id1168914093?mt=8

## 5 招聘职位
Go工程师 （拉勾详情页请移步 [https://www.lagou.com/jobs/3954291.html](https://www.lagou.com/jobs/3954291.html)）

### 岗位职责：                                                      

1、高并发HTTP接口设计、开发与迭代
2、微服务及中间件开发维护
3、研究高稳定性、高可用性的系统架构设计

### 岗位要求：                                                    

1、3年以上Golang开发经验，本科学历
2、熟悉Linux环境下的go语言开发
3、熟悉socket、HTTP等相关技术     
4、熟悉redis、memcache、mysql、kafka、nginx、hbase、Consul、Docker等优先 
5、有大型互联网开发经验优先
6、具备较强的逻辑思维和沟通能力，为团队提供可行的前沿的架构方案。
7、熟悉PHP者优先，本科以上学历 

## 7.薪酬待遇
月薪25K~50K。每季度有绩效评估和奖金发放。年底奖金。推荐人才另有奖励。

## 8.福利

- 弹性工作
- 带薪年假
- 定期培训
- 不定期团建
- 包三餐
- 入职MacBookPro

## 9.简历投递

BOSS直聘、拉勾等网站上搜索“一下科技”，选择对应职位并投递简历。
直接发邮件给我[niuqiang@yixia.com]。

**Comment by hyper0x** [comment]
请参照[模板](https://github.com/GoHackers/jobs/blob/master/recruit_template.md)请改一下。

**Comment by hyper0x** [comment]
另外最好加入一些标签，以便大家查找。

**Comment by jony4** [comment]
@hyper0x 麻烦帮忙加下标签
